  services:
    mongo:
      image: mongo
      container_name: mongo
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      networks:
        - app-network

    authservice:
      build: ./auth_service
      container_name: authservice
      ports:
        - "8080:8080"
      depends_on:
        - mongo
        - discovery-service

      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      networks:
        - app-network

    userservice:
      build: ./user_service
      container_name: userservice
      ports:
        - "8081:8081"
      depends_on:
        - mongo
        - discovery-service
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      networks:
        - app-network

    restaurantservice:
      build: ./restaurant_service
      container_name: restaurantservice
      ports:
        - "8082:8082"
      depends_on:
        - mongo
        - discovery-service
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      networks:
        - app-network

    orderservice:
      build: ./order_service
      container_name: orderservice
      ports:
        - "8083:8083"
      depends_on:
        - mongo
        - discovery-service

      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      networks:
        - app-network

    analytics1service:
      build: ./analytics1_service
      container_name: analytics1service
      ports:
        - "8084:8084"
      depends_on:
        - mongo
        - discovery-service

      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      networks:
        - app-network

    apigateway:
      build: ./api_gateway
      container_name: apigateway
      ports:
        - "8079:8079"
      depends_on:
        - authservice
        - userservice
        - restaurantservice
        - orderservice
        - analytics1service
        - discovery-service

      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      networks:
        - app-network

    zookeeper:
      image: confluentinc/cp-zookeeper:7.3.2
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      networks:
        - app-network

    kafka:
      image: confluentinc/cp-kafka:7.3.2
      container_name: kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      depends_on:
        - zookeeper
      networks:
        - app-network

    discovery-service:
      build: ./discovery_service
      container_name: discovery-service

      environment:
        - EUREKA_INSTANCE_HOSTNAME=discovery-server
        - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
        - EUREKA_CLIENT_FETCH_REGISTRY=false

      ports:
        - "8761:8761"
      networks:
        - app-network

  volumes:
    mongo_data:

  networks:
    app-network:
      driver: bridge
